### ISSUE TITLE
Add documentation around how and when to use different variable scopes.

### ISSUE THREAD

**Issue by prashantagarwal** [postmanlabs/postman-docs#1442]
Currently in Postman documentation around variables we do explain different types of variable scopes but do not provide enough context on "when to use which type of scope". With 4 types of scopes users have a lot of confusion around which variable should they use, how to manage them etc.

**Comment by tparikka** [comment]
@sivcan Is there any movement on this item? I'm hoping for clarification on how variable scopes work and the docs could really use some more clarity.

**Comment by vdespa** [comment]
@tparikka As this has been causing a lot of confusion and the documentation has still not been updated, I decided to write an article on this topic: https://medium.com/@vdespa/demystifying-postman-variables-how-and-when-to-use-different-variable-scopes-66ad8dc11200

I hope this helps and I am open to any feedback that you might have.

**Comment by ArifPMan** [comment]
This issue has been addressed. So, closing it.

**Comment by tparikka** [comment]
@arifpmam how was the issue resolved? I still don't see documentation on variable scope in the official documentation and a third party Medium post seems like a poor substitute to the company's own docs.

**Comment by vdespa** [comment]
@ArifPMan I must agree with @tparikka. It would be great if you could share a link to the respective documentation.

Additionally, since the community has raised this issue, it would not hurt to ask for feedback if the issue has been resolved as expected.

**Comment by ArifPMan** [comment]
This is still unresolved. Will get back to you soon.

**Comment by SueSmith** [comment]
Just a headsup that I'm currently redrafting the variables doc and hoping to provide a little more detail to address this at least in part.. Will refer to @vdespa's amazing article.. 😀

**Comment by SueSmith** [comment]
Added detail in new version of variables doc #2028 but if more is still required please give me a shout 😬

**Comment by vdespa** [comment]
@SueSmith  I think the main issue has not been addressed yet or I have overlooked something.

**Comment by SueSmith** [comment]
@vdespa did you see the new version of the variables.md file? it includes the advice from your medium post

**Comment by SueSmith** [comment]
@vdespa it's a large diff so may not render by default if you're viewing the changes in github web interface, if you look for it and expand you should see a lot of new material

**Comment by vdespa** [comment]
> @vdespa did you see the new version of the variables.md file? it includes the advice from your medium post

Indeed, I have missed that 🙈. 
I have added some comment but overall great work👏

**Comment by SueSmith** [comment]
@vdespa thanks for the input, made a few adjustments and will add more detail on local scope if I get any more info from the team
