### ISSUE TITLE
Request to remove sync screenshot from docs

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-docs#2183]
As disabling sync option is removed from the application, can we please remove this particular section from the following document:

https://learning.postman.com/docs/postman/monitors/troubleshooting-monitors/#debugging-local-run-attempts

Screenshot:

<img width="1041" alt="Screenshot 2020-02-13 at 4 22 52 PM" src="https://user-images.githubusercontent.com/47771757/74428395-ebf88500-4e7e-11ea-8ed9-92ac06f47874.png">

**Comment by Raj-postman** [comment]
Not sure if this is being tracked somewhere but this https://github.com/postmanlabs/postman-docs/issues/1697 section needs to checked again.

**Comment by arlemi** [comment]
@Raj-postman I believe @claireriley is currently updating the monitoring docs so this would probably fall into it?

Regarding #1697, the page says deprecated at the top and can't be accessed apart by searching for team library. We need to look into why it still shows in search results though. 🤔

**Comment by loopDelicious** [comment]
@Raj-postman this one has been fixed by the monitoring updates. Feel free to reopen if you have more to add.

**Comment by Raj-postman** [comment]
@loopDelicious I still see the screenshot of disabling sync in that document there:

It should be removed or else it's bound to create confusion 😓 

Current screenshot:

![image](https://user-images.githubusercontent.com/47771757/94174720-48129580-feb3-11ea-9a27-39940854a20a.png)

Actual Settings Modal:

![image](https://user-images.githubusercontent.com/47771757/94174586-20233200-feb3-11ea-9fa5-84263621f3ff.png)

**Comment by loopDelicious** [comment]
Ah, I see it now. Sounds like we just need to remove the bullet and screenshot 👍
